### ISSUE TITLE
any guide how to run the examples?

### ISSUE THREAD

**Issue by ipeisong** [pmlopes/yoke#141]
First run gradle from kitcms doesn't work.

Then I tried '../../gradlew -i runMod', with this error:
```
java.lang.NoSuchMethodError: com.jetdrone.vertx.yoke.Yoke.engine(Ljava/lang/String;Lcom/jetdrone/vertx/yoke/Engine;)Lcom/jetdrone/vertx/yoke/Yoke;
	at com.jetdrone.vertx.kitcms.KitCMS.start(KitCMS.java:37)
	at org.vertx.java.platform.Verticle.start(Verticle.java:82)
	at org.vertx.java.platform.impl.DefaultPlatformManager$21.run(DefaultPlatformManager.java:1750)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Failed in deploying module
java.lang.NoSuchMethodError: com.jetdrone.vertx.yoke.Yoke.engine(Ljava/lang/String;Lcom/jetdrone/vertx/yoke/Engine;)Lcom/jetdrone/vertx/yoke/Yoke;
	at com.jetdrone.vertx.kitcms.KitCMS.start(KitCMS.java:37)
	at org.vertx.java.platform.Verticle.start(Verticle.java:82)
	at org.vertx.java.platform.impl.DefaultPlatformManager$21.run(DefaultPlatformManager.java:1750)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
:examples:kitcms:runMod (Thread[Daemon Thread 4,5,main]) completed. Took 0.302 secs.
```
Just cannot get it started. What's wrong here? Thanks.

**Comment by pmlopes** [comment]
now that the moving to maven is complete you can run any example like:

`> cd examples/kitcms && mvn clean install vertx:runMod`

if you have an error about missing yoke because you have a snapshot version, then just build it form the root:

`> mvn clean install`
